Add support for Graphite web exponentialMovingAverage function
grafana/carbonapi pull request #16
Opened 2022-06-10 16:29 UTC by carrieedwards

This PR adds support for the Graphite web exponentialMovingAverage() function.

2022-06-16 14:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/carbonapi?pullRequest=16) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/carbonapi?pullRequest=16) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/carbonapi?pullRequest=16) it.</sub>

2022-07-19 14:16 UTC, ywwg commented
windowed.go has a subtle bug around floating point arithmatic. I used to do a moving average interview question so this is top of mine for me.  The current algorithm keeps a sum value, and continually adds the new value to the sum and subtracts the oldest value from it. It's a running sum that avoids needing to add up all of the values in the array every time.  However, floating point does not technically work correctly this way.  Continually adding and subtracting from the single sum value will eventually cause drift over time.  Instead, we need to periodically recalculate the sum to eliminate the drift.  That could be done every X calls to push

2022-08-01 16:28 UTC, carrieedwards commented
Do you have a recommendation for how frequently to re-calculate the sum?

2022-08-02 18:41 UTC, ywwg commented
how about every 1000 points?

2022-08-03 18:35 UTC, ywwg requested changes

2022-08-03 18:35 UTC, ywwg commented on expr/functions/exponentialMovingAverage/function.go
> +		for i, v := range a.Values {
in the python version, the period before the window size (previewSeconds) is copied as-is and is not calculated using the exp function. https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L1430

2022-08-03 18:35 UTC, ywwg commented on expr/types/windowed.go
> +func NewExpMovingAverage(constant float64) *ExpWindowed {
I think it might be clearer if this object took the window size as an argument and then calculated the constant itself.  Also, it should handle the logic of skipping previewSeconds samples before returning calculated results.  Right now the logic is split between this object and the caller.  We want this object to contain all of the tricksy logic and let the caller use it transparently.

2022-08-04 17:51 UTC, ywwg requested changes

2022-08-04 17:51 UTC, ywwg commented on expr/types/windowed.go
> +func (w *ExpWindowed) Push(x float64) {
so I know I asked for this but this doesn't feel right now, sorry.  I don't understand how the python works, really, but it doesn't keep a data window.  Let's just translate the python code as closely as we can, keeping as much of the logic in this object as possible.

2022-08-04 17:58 UTC, npazosmendez commented on expr/types/windowed.go
> +func (w *ExpWindowed) Push(x float64) {
I think it's Graphite's terminology that is causing confusion by using the word "window". If I understand correctly, an EMA is just a weighted average that takes into account all the history of data but considers the recent one more important, check out this article: https://www.investopedia.com/terms/e/ema.asp (and also notice it's not using the "window" word). It's like a smoothing function

2022-08-04 20:30 UTC, npazosmendez reviewed
I think we need to add `exponentialMovingAverage` to this list like all the other moving* functions:

https://github.com/grafana/carbonapi/blob/cedwards/add-exponentialMovingAverage-function/pkg/parser/parser.go#L188

That would make the fetching of the data to be done since `from-windowSize`. Check out the python version:

https://github.com/graphite-project/graphite-web/blob/2ec4b6cf25b3d71bead44579b8a6d19f2c83bae5/webapp/graphite/render/functions.py#L1413-L1419

Apart from that I think it looks great :+1:

2022-08-04 20:30 UTC, npazosmendez commented on expr/functions/exponentialMovingAverage/function.go
> +		ema := consolidations.AggMean(a.Values[:windowSize])
We should check this `windowSize` is in the range `[ 1..len(a.Values) )`. Just did a quick test and passing negative values or greater than `len(..)-1` cause panics. The python version accepts this because the slicing is very flexible, but I'm thinking we could just error at the top with `fmt.Errorf("invalid window size ..` or something?

2022-08-04 20:44 UTC, ywwg requested changes
yeah I think this is the way to go. thanks!

2022-08-04 20:44 UTC, ywwg commented on expr/functions/exponentialMovingAverage/function.go
> +		argstr = fmt.Sprintf("%q", e.Args()[1].StringValue())
we probably need error-checking on the string parsing here

2022-08-04 20:44 UTC, ywwg commented on expr/helper/helper.go
> +func Round(x float64, precision int) float64 {
let's call this SafeRoundTo since it handles NaN and supports precision

2022-08-04 20:44 UTC, ywwg approved these changes

2022-08-08 17:54 UTC, merged