Update tags handling in expr functions to match Graphite web
grafana/carbonapi pull request #22
Opened 2022-06-30 15:06 UTC by carrieedwards

This PR updates expr functions to add function-specific tags to match Graphite web functions.

2022-07-18 15:18 UTC, npazosmendez commented
Also, it looks like metrictank is making sure not to modify the input series: https://github.com/grafana/metrictank/blob/master/expr/func_absolute.go#L33 . Not sure how relevant that is either.

2022-07-19 14:46 UTC, ywwg requested changes
looks mostly fine, just a few questions

2022-07-19 14:46 UTC, ywwg commented on expr/functions/multiplySeriesWithWildcards/function.go
> +			if commonTags[k] != v {
do you need to test that k is in commonTags? or does that just return nil in Go? I forget

2022-07-19 14:46 UTC, ywwg commented on expr/functions/multiplySeriesWithWildcards/function.go
> +		if _, ok := commonTags["name"]; !ok {
this is what I thought you might have to do above

2022-07-19 14:50 UTC, npazosmendez commented
> Also, it looks like metrictank is making sure not to modify the input series: https://github.com/grafana/metrictank/blob/master/expr/func_absolute.go#L33 . Not sure how relevant that is either.

BUMP. This is why tests now have to use `TestEvalExpr` instead of `TestEvalExprModifiedOrigin`. Do we care if these functions change the input data?

2022-07-19 16:19 UTC, npazosmendez commented
FTR: I'll take care of the input data immutability issue, just talked with Carrie.

 > Do we want the changes to modifying input data to be a separate PR?
I'd prefer to keep everything in this same PR,it shouldn't make the diff much larger

2022-07-19 18:30 UTC, merged