Add powSeries function
grafana/carbonapi pull request #42
Opened 2022-07-29 20:02 UTC by leizor

2022-08-01 13:49 UTC, ywwg requested changes
the algorithm has some wierdness to it, I left some notes.  I think it can be simplified and greatly sped up.

Can you write a short Go Benchmark test for this function? https://blog.logrocket.com/benchmarking-golang-improve-function-performance/ etc

2022-08-01 13:49 UTC, ywwg commented on expr/functions/powSeries/function.go
> +				vals := m.GetValues()
we are calling getvalues for every single iteration, and since this algorithm is n*m that could be very slow.  Instead I think we should precache m.GetValues()... maybe that's what was intended with the clone behavior above? make metricdata a slice of slice of values?

2022-08-01 13:54 UTC, ywwg commented on expr/functions/powSeries/function.go
> +				vals := m.GetValues()
(there is a nil check for getvalues... I think it's worth precaching even just to avoid n*m redundant nil checks)

2022-08-01 17:42 UTC, leizor commented on expr/functions/powSeries/function.go
> +	functions := []string{"powSeries"}
🤷‍♂️  Yea, I thought it was weird, but it's also how every other function does it. I just considered it boilerplate and copied/pasted it over.

2022-08-01 17:59 UTC, leizor commented on expr/functions/powSeries/function.go
> +		if len(metricData) == len(series) {
Oops yea, nice catch. Not sure what I was thinking...

2022-08-01 18:00 UTC, leizor commented on expr/functions/powSeries/function.go
> +				vals := m.GetValues()
Will do!

2022-08-02 13:28 UTC, ywwg commented on expr/functions/powSeries/function.go
> +	functions := []string{"powSeries"}
@carrieedwards do you know why this pattern exists?  I'd like to clean it up if there's no good reason for it.

2022-08-02 13:32 UTC, ywwg approved these changes
I'd still like to simplify the New function unless we have a good reason not to, but otherwise good

2022-08-02 13:32 UTC, ywwg commented on expr/functions/powSeries/function.go
> +	metricData := make([][]float64, 0, len(series))
let's call this seriesValues since it's from a GetValues call

2022-08-02 13:39 UTC, npazosmendez commented on expr/functions/powSeries/function.go
> +	functions := []string{"powSeries"}
Some of the `function.go` can process different expressions so they register different names (example: https://github.com/grafana/carbonapi/blob/main/expr/functions/below/function.go#L25); sometimes it's just aliases and sometimes it's variations of the function (min/max etc).
So I think this is why this pattern exists, it's just copypasted all over the functions. I guess one could argue it's easier to add an alias `powS` in the future here, but not a big deal IMO.

2022-08-02 13:40 UTC, ywwg commented on expr/functions/powSeries/function.go
> +	functions := []string{"powSeries"}
I guess if we're trying to minimize drift from upstream, it's better to just keep the silliness. leave it

2022-08-02 13:44 UTC, npazosmendez commented on expr/functions/powSeries/function.go
> +	functions := []string{"powSeries"}
I agree

2022-08-02 16:59 UTC, merged