Fix upstream merge conflicts
grafana/carbonapi pull request #62
Opened 2022-08-09 19:48 UTC by npazosmendez

Original PR: https://github.com/grafana/carbonapi/pull/60

This PR has the same changes but with a different  workflow to make review easier. This is what I did:
1. Created the branch `npazosmendez/sync-upstream2` and merged the upstream changes there. Commited everything blindly, with conflicts included.
2. From `npazosmendez/sync-upstream2`  I branched to `npazosmendez/sync-upstream-fix-conflicts`, where I compressed all the fixes to the conflicts in a single commit.
3. Created this PR that merges `npazosmendez/sync-upstream2` <--  `npazosmendez/sync-upstream-fix-conflicts` . This makes the diff of this PR just have the fixes to the conflicts and nothing else

Once this PR is approved we can then  merge `npazosmendez/sync-upstream2` into `main`.

Note that I'm still missing some fixes. Those will come in separate commits, but the diff should still be clean.

2022-08-09 20:55 UTC, ywwg commented
as said in slack:

The problem is this will either:

1. squash down so our changes and the upstream merge will be in one commit, which will make future merges from HEAD hard (because the history will not be shared)
2. if unsquashed, there will be completely broken commits with the conflict markers

I think we need to merge in from HEAD unsquashed I think, and do the fixes in the single merge commit

2022-08-09 21:05 UTC, jesusvazquez commented
Maybe it helps to know how we keep https://github.com/grafana/mimir-prometheus/ up to date with github.com/prometheus/prometheus/

When we want to update mimir-prometheus with upstream changes, a separate PR is open, for example https://github.com/grafana/mimir-prometheus/pull/287 This PR is always merged with a **Merge commit** not a squash.

Then any changes performed on top of the mimir-prometheus fork are merged from separate prs and they can either be squashed commits or merged commits but usually they prefer squashed commits to keep 1 commit 1 pr parity.

The benefits of this workflow is that you can always compare the fork to upstream and cherry pick any of the changes done in the fork.

2022-08-09 21:12 UTC, npazosmendez commented
@jesusvazquez are always all the merge conflicts (and associated fixes) contained in the `Merge` commit? Or can those conflicts be resolved incrementally?

2022-08-09 21:24 UTC, npazosmendez commented
Ok this is what I'm thinking:
1. We use this PR for reviewing
2. Once approved, I use the diff `npazosmendez/sync-upstream2`  vs `npazosmendez/sync-upstream-fix-conflicts` to create a patch that solves all the conflicts.
3. In a new branch `X`, I do the merge from scratch and use the patch to solve the conflicts. Then commit the Merge.
4. We open a new PR `main` <-- `X` and merge it without squash to keep all the commits

2022-08-09 21:53 UTC, jesusvazquez commented
> @jesusvazquez are always all the merge conflicts fixes contained in the Merge commit? Or can those conflicts be resolved incrementally?

Any conflicts that may surface are addressed in the same PR as separate commits and then the entire PR is merged not squashed.

2022-08-10 15:22 UTC, ywwg requested changes
ran out of steam but here are my comments so far

2022-08-10 15:22 UTC, ywwg commented on expr/functions/aliasByMetric/function.go
>  		name := part[len(part)-1]
why are we not copying the tags or values?

2022-08-10 15:22 UTC, ywwg commented on expr/functions/aliasByNode/function_test.go
> +		// FIXME: I don't think `metric1.foo==.bar.baz` is a valid metric name, that is making this test fail
please attach an Issue number to this

2022-08-10 15:22 UTC, ywwg commented on expr/functions/groupByNode/function_test.go
> +		// FIXME: I don't think `..foo==.bar` is a valid metric name, that is making these testsapi/cmd/carbonapi/ht fail
ibid, same issue as above

2022-08-10 15:35 UTC, carrieedwards commented on expr/functions/aliasByPostgres/function.go
>  			r := a.CopyName(tempName)
Does CopyName do the same changes that CopyLink did?

2022-08-10 15:41 UTC, carrieedwards commented on expr/functions/nPercentile/function.go
> +		r := a.CopyLink()
In some places, CopyName is used, and in some, CopyLink is used. What is the difference?

2022-08-10 15:42 UTC, carrieedwards commented on expr/functions/removeBelowSeries/function.go
> +	"fmt"
is this import being used?

2022-08-10 15:42 UTC, carrieedwards commented on expr/functions/smartSummarize/function.go
> +	"fmt"
is the import being used?

2022-08-10 15:47 UTC, npazosmendez commented on expr/functions/removeBelowSeries/function.go
> +	"fmt"
Yes. The merge deleted it and I had to add it again to fix the build. The build would fail if it wasn't being used anyway.

2022-08-10 15:47 UTC, npazosmendez commented on expr/functions/smartSummarize/function.go
> +	"fmt"
ditto

2022-08-10 15:49 UTC, npazosmendez commented on expr/functions/aliasByPostgres/function.go
>  			r := a.CopyName(tempName)
Yes, check it out: https://github.com/grafana/carbonapi/blob/npazosmendez/sync-upstream-fix-conflicts/expr/types/types.go#L457-L461

2022-08-10 15:53 UTC, npazosmendez commented on expr/functions/nPercentile/function.go
> +		r := a.CopyLink()
CopyName is a new helper function the upstream introduced, check the behavior here: https://github.com/grafana/carbonapi/blob/npazosmendez/sync-upstream-fix-conflicts/expr/types/types.go#L452

I think it could be avoided. (there's lots of helpers that do almost the same thing (and sometimes the same thing): Copy, CopyLink, CopyName, CopyTag, CopyLinkTags, etc etc etc).

But I think changing that is out of the scope of this PR, wanted to leave the upstream changes as clean as possible.

2022-08-10 15:57 UTC, leizor commented on expr/functions/nPercentile/function.go
> +		r := a.CopyLink()
Looking forward to having `CopyName` be available! There's a lot of places where I've seen something like this happening:

```
md := origMd.CopyLink()
md.Name = "new name"
...
```

The problem with that is that the "name" tag then doesn't get updated correctly, but it looks like `CopyName` covers that.

2022-08-10 16:32 UTC, npazosmendez commented on expr/functions/groupByNode/function_test.go
> +		// FIXME: I don't think `..foo==.bar` is a valid metric name, that is making these testsapi/cmd/carbonapi/ht fail
Done

2022-08-10 16:32 UTC, npazosmendez commented on expr/functions/aliasByNode/function_test.go
> +		// FIXME: I don't think `metric1.foo==.bar.baz` is a valid metric name, that is making this test fail
Done

2022-08-10 16:48 UTC, carrieedwards approved these changes
Looks good to me

2022-08-10 17:58 UTC, ywwg approved these changes

2022-08-10 18:17 UTC, leizor approved these changes
🚀

2022-08-10 18:30 UTC, closed without merging